### ISSUE TITLE
type mismatch for ZydisMnemonic and ZydisMnemonics

### ISSUE THREAD

**Issue by williballenthin** [zyantific/zydis-rs#18]
I'd like to inspect the mnemonic of decoded instructions in order to find specific instructions. This is not as easy as I'd like because of a type mismatch between the mnemonic constants and the mnemonic field.

A `ZydisDecodedInstruction_` has a field `mnemonic` with type `ZydisMnemonic`:

![image](https://user-images.githubusercontent.com/156560/56844336-0ae44700-686c-11e9-8b1e-acb9e6317c7b.png)

`ZydisMnemonic` is an alias for `u16`:

![image](https://user-images.githubusercontent.com/156560/56844344-2bac9c80-686c-11e9-957f-5bfc3b859ee0.png)

The mnemonic constants exported have type `ZydisMnemonics`:

![image](https://user-images.githubusercontent.com/156560/56844355-539c0000-686c-11e9-9858-5ba41c7661c0.png)

And, unfortunately, `ZydisMnemonics` is an alias for `c_uint`:

![image](https://user-images.githubusercontent.com/156560/56844360-70d0ce80-686c-11e9-9d86-3cc506855ff1.png)

This prevents me from directly comparing the mnemonic field of a decoded instruction to a constant exported by Zydis:

![image](https://user-images.githubusercontent.com/156560/56844371-8c3bd980-686c-11e9-88fd-fe9b99df6734.png)

![image](https://user-images.githubusercontent.com/156560/56844384-b1304c80-686c-11e9-81ff-0c6b13feff77.png)

Would you consider changing the type of `ZydisMnemonic` or `ZydisMnemonics` so that they are the same?

**Comment by williballenthin** [comment]
Of course, I can cast the `mnemonic` field as an `i32`; however, it seems like I shouldn't have to do this manually.

![image](https://user-images.githubusercontent.com/156560/56844447-8eeafe80-686d-11e9-849f-64ba4ee677dd.png)

**Comment by th0rex** [comment]
Yes, this is an artifact of the currently released version on `crates.io` using bindgen and using a released zydis version. Zydis v2.0.3 (the latest release) used to `typedef ZydisU16 ZydisMnemonic;` and then have a seperate `enum ZydisMnemonics` with all the values (see [here](https://github.com/zyantific/zydis/blob/v2.0.3/include/Zydis/Generated/EnumMnemonic.h#L4-L9) for more context). Thus bindgen also generates two different types for that.

On the current master branch, we've moved away from bindgen for various reasons, and also are tracking the zydis development branch, instead of a tagged release, so the problem you're having doesn't exist there anymore. I'm holding off a release on `crates.io` until a new zydis version gets officially released. I think in the meantime your only option is to either life with the casts, or use these bindings from git directly (theres an example in the readme). There have been some breaking changes however, all enums are now properly scoped. `ZYDIS_MNEMONIC_JMP` would turn into `Mnemonic::JMP`, etc. As far as I remember all the other breaking changes should only involve the formatter, and especially only formatter hooks.

**Comment by williballenthin** [comment]
thanks for the explanation, @th0rex!

I think for the time being I'll cast things explicitly, but definitely intend to upgrade once the new release is out.

**Comment by williballenthin** [comment]
as a short updated, i've updated my project to use zydis-rs master, and things are much nicer here. it was easy to switch over, and the types are better. nice work!
